name: flutter_verification_code
homepage: https://github.com/awaik/flutter_verification_code.git
description: A Flutter package that help you create a verification input.
version: 1.1.2+1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter